### ISSUE TITLE
Update Grunt dependency

### ISSUE THREAD

**Issue by nvaken** [jharding/grunt-exec#70] opened 2016-04-21 06:51 UTC
Currently on `~0.4`, should be fixed since this will prevent projects from upgrading to the latest version of Grunt.

**Comment by gwicksted** [comment] 2016-04-27 15:57
Please post new version to npm as soon as you have time!

**Comment by panther7** [comment] 2016-04-28 08:09
+1

**Comment by TheSavior** [comment] 2016-04-28 19:12
Duplicate of https://github.com/jharding/grunt-exec/pull/68

**Comment by markusbrunner-design** [comment] 2016-05-10 08:03
+1

**Comment by markusbrunner-design** [comment] 2016-05-10 08:04
npm install grunt grunt-exec

npm ERR! peerinvalid The package grunt@1.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-exec@0.4.6 wants grunt@~0.4
npm ERR! peerinvalid Peer grunt-bump@0.8.0 wants grunt@>=1.0.1
npm ERR! peerinvalid Peer open-xchange-shared-grunt-config@0.12.4 wants grunt@>=0.4.5
npm ERR! peerinvalid Peer grunt-contrib-concat@1.0.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-require-gettext@0.8.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-contrib-clean@1.0.0 wants grunt@>= 0.4.5
npm ERR! peerinvalid Peer grunt-contrib-jshint@1.0.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-newer@1.2.0 wants grunt@>=0.4.1
npm ERR! peerinvalid Peer grunt-check-dependencies@0.12.0 wants grunt@>=0.4.5

**Comment by Miw0** [comment] 2016-05-10 10:20
Hey guys, just use https://github.com/sindresorhus/grunt-shell which is up-to-date :)

**Comment by markusbrunner-design** [comment] 2016-05-10 10:37
if this wouldn't be 3rd-party-code - why not...

**Comment by gwicksted** [comment] 2016-05-10 13:52
Thank you @Miw0, I'll try it out as an alternative.  This repo appears to be dead which is unfortunate given the 5k downloads per day.

**Comment by gwicksted** [comment] 2016-05-10 15:29
Hi @markusbrunner-design I have forked this repo, resolved js-lint issues, resolved win32 issues, resolved package.json license issue, got a travis CI build going, and have reached out to NPM and @jharding to hopefully replace grunt-exec with this new community-driven variation.  Repo here: https://github.com/gwicksted/grunt-exec

**Comment by panther7** [comment] 2016-05-11 19:08
gwicksted: Thanks, now "upload to" https://www.npmjs.com/package/grunt-exec ;-)

**Comment by gwicksted** [comment] 2016-05-11 20:46
@panther7 coming soon! @jharding has added myself as an owner of the npmjs grunt-exec package.  He has also offered to allow me to modify this repo instead of maintaining the fork which would be great.

**Comment by Miw0** [comment] 2016-05-11 21:12
Really nice news! Thank you for overtaking this repo :)

Von meinem iPhone gesendet

**Comment by gwicksted** [comment] 2016-05-12 03:02
Fixed in 0.4.7 (latest)

**Closed by gwicksted** 2016-05-12 03:02 UTC

**Comment by markusbrunner-design** [comment] 2016-05-12 07:20
@gwicksted Thanks!!!
